### ISSUE TITLE
Out of memory caused by NativeScaler

### ISSUE THREAD

**Issue by ZhenYangIACAS** [Alpha-VLLM/LLaMA2-Accessory#31]
We install the toolkits as described in requirements.txt. 
When we run full-parameter SFT on 8 A100, the bug of OOM occurs at:

init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda    .Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward passOutOfMemoryError
: torch.cudaCUDA out of memory. Tried to allocate 774.00 MiB (GPU 2; 31.75 GiB total capacity; 29.34 GiB already allocated; 729.75 MiB free; 29.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.
OutOfMemoryError: CUDA out of memory. Tried to allocate 774.00 MiB (GPU 4; 31.75 GiB total capacity; 29.34 GiB already allocated; 697.75 MiB free; 29.39 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

This error occurs caused by NativeScalerWithGradNormCount in misc.py:
565             with model.no_sync():
566                 self._scaler.scale(loss).backward(create_graph=create_graph)

Can you provide some suggestions to fix this error.

**Comment by ChrisLiu6** [comment]
Could you provide the detailed commands you run for the experiment?

**Comment by ZhenYangIACAS** [comment]
The command I use is:
torchrun --nproc_per_node=8 \
        --master_port=1111 \
    $code_dir/main_finetuning.py \
    --model Llama7B_adapter \
    --llama_model_path $llama_model_dir \
    --train_data_path $curr_dir/configs/v5/vqkd_32_8192/SFT.train.coco.yaml \
    --val_data_path $curr_dir/configs/v5/vqkd_32_8192/SFT.val.coco.yaml \
    --output_dir $output_dir \
    --resume $output_dir/epoch1 \
    --train_L2V \
    --unfreeze_layer 0 \
    --adapter_len 0 \
    --adapter_layer 0 \
    --img_vocab_size 8192 \
    --img_dim 32 \
    --img_embedding_path $img_embedding_path \
    --max_seq_len 512 \
    --batch_size 1\
    --accum_iter 24 \
    --lr 3e-5 \
    --epochs 5 \
    --warmup_epochs 2 \
    --weight_decay 0.1 \
    --split_epoch 40 \
    --distributed \
    --precision 'fp16' \
    --freeze_img_output \
    --log_dir $output_dir/log >$output_dir/train.log 2>&1

**Comment by ChrisLiu6** [comment]
Well, it seems that you have changed the codes a lot. As I don't know the inner details of your code, it's hard to tell where the problem is. Maybe you can first try our exemplary experiments [here](https://github.com/Alpha-VLLM/LLaMA2-Accessory/tree/main/accessory/exps) so that we can provide better support. Moreover, since your log says that the GPU has 32G memory, I guess you are using V100 instead of A100, whose memory may not be enough to run some large experiments (e.g. full fine-tuning with large model) in our provided default setting. However, generally speaking, 7B + LLaMA-Adapter is a relatively efficient setting, so I tend to think there are other bugs.

**Comment by ZhenYangIACAS** [comment]
@ChrisLiu6 Ok, thanks. I have re-produce your experiment by the following command:
torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 \
        --master_port=1112 \
    $code_dir/main_finetune.py \
     --output_dir $output_dir \
    --epochs 100 \
    --warmup_epochs 2 \
    --batch_size 2 \
    --accum_iter 32 \
    --num_workers 4 \
    --max_words 512 \
    --lr 0.00003 --min_lr 0.000005 --clip_grad 2 --weight_decay 0.02 \
    --data_parallel "$data_parallel" --model_parallel_size "$model_parallel" --checkpointing \
    --llama_type llama --llama_config "$llama_config" --tokenizer_path "$tokenizer_path" \
    --no_visual \
    --precision 'fp16' \
    --pretrained_path "$pretrained_path" --pretrained_type="$pretrained_type" \
    --data_config $data_config
Now, it runs ok. But I find that its log about grad_norm is inf. Is it expected?
16:49:23.381571] Epoch: [0]  [0/3232]  lr: 0.000000  closs: 1.7357 (1.7357)  time: 3.9980  data: 0.5492  max mem: 17120
[16:49:42.848763] Epoch: [0]  [10/3232]  lr: 0.000000  closs: 1.7357 (1.6650)  time: 2.1331  data: 0.0501  max mem: 18632
[16:50:02.322553] Epoch: [0]  [20/3232]  lr: 0.000000  closs: 1.6979 (1.6548)  time: 1.9469  data: 0.0002  max mem: 18632
[16:50:21.714853] Epoch: [0]  [30/3232]  lr: 0.000000  closs: 1.6088 (1.6037)  time: 1.9432  data: 0.0002  max mem: 18632
[16:50:41.742549] Epoch: [0]  [40/3232]  lr: 0.000000  closs: 1.6047 (1.6127)  grad_norm: inf (inf)  time: 1.9709  data: 0.0002  max mem: 18632
[16:51:01.339432] Epoch: [0]  [50/3232]  lr: 0.000000  closs: 1.6490 (1.6429)  grad_norm: inf (inf)  time: 1.9811  data: 0.0002  max mem: 18632
[16:51:20.899910] Epoch: [0]  [60/3232]  lr: 0.000000  closs: 1.5530 (1.6248)  grad_norm: inf (inf)  time: 1.9578  data: 0.0002  max mem: 18632
[16:51:40.273890] Epoch: [0]  [70/3232]  lr: 0.000000  closs: 1.6010 (1.6251)  grad_norm: inf (inf)  time: 1.9466  data: 0.0002  max mem: 18632

**Comment by ChrisLiu6** [comment]
This is not expected. This problem should be related to the overflow of fp16 grads. However, this problem should only affect the statistical values and should not impact normal training, since the grad scaler will not call `optimizer.step` when inf is found in grad. We have not met this problem likely because we've been always using the bf16 data type, which, however, is not compatible with V100. We've just fixed this issue in the last commit:
https://github.com/Alpha-VLLM/LLaMA2-Accessory/blob/803000ff78ad22d933f7b4078a4b819273aa906d/accessory/engine_finetune.py#L66

You may pull the latest version to try.
